# ------------------------------------------------------------
# In this file, you can make some modifications to the Streamlit
# app's global environment. 
#
# All of the possible config options can be found here:
# https://docs.streamlit.io/develop/api-reference/configuration/config.toml
# ------------------------------------------------------------


[client]
# Turning the default sidebar navigation off so we 
# can use our own
showSidebarNavigation = false

[theme]
primaryColor = "#3498db"      
backgroundColor = "#f8f9fa"   
secondaryBackgroundColor = "#ffffff"
textColor = "#2c3e50"        
font = "sans serif"

